"""nfl schedule

Revision ID: b937206114ea
Revises: d6caea54447a
Create Date: 2026-09-09 19:26:52.996316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b937206114ea'
down_revision: Union[str, Sequence[str], None] = 'd6caea54447a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=8), nullable=False),
    sa.Column('away_team', sa.String(length=8), nullable=False),
    sa.Column('kickoff', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'week', 'home_team', name='uq_nfl_game')
    )
    op.create_index(op.f('ix_nfl_games_season'), 'nfl_games', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nfl_games_season'), table_name='nfl_games')
    op.drop_table('nfl_games')
    # ### end Alembic commands ###
