"""player ownership percentages

Revision ID: d6caea54447a
Revises: eb0a26031406
Create Date: 2026-09-06 19:23:43.897569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6caea54447a'
down_revision: Union[str, Sequence[str], None] = 'eb0a26031406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # (Dropped an autogenerated alter_column tightening leagues.source to NOT
    # NULL: SQLite can't ALTER COLUMN, and nullable-with-default is harmless.)
    op.add_column('players', sa.Column('percent_owned', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('percent_started', sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('players', 'percent_started')
    op.drop_column('players', 'percent_owned')
