"""baseline schema

Revision ID: eb0a26031406
Revises: 
Create Date: 2026-09-06 15:08:32.759802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0a26031406'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_key', sa.String(length=32), nullable=False),
    sa.Column('game_key', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('is_keeper', sa.Boolean(), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=True),
    sa.Column('scoring_type', sa.String(length=32), nullable=True),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_league_key'), 'leagues', ['league_key'], unique=True)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('nfl_team', sa.String(length=8), nullable=True),
    sa.Column('injury_status', sa.String(length=16), nullable=True),
    sa.Column('bye_week', sa.Integer(), nullable=True),
    sa.Column('yahoo_id', sa.String(length=16), nullable=True),
    sa.Column('sleeper_id', sa.String(length=16), nullable=True),
    sa.Column('espn_id', sa.String(length=16), nullable=True),
    sa.Column('fantasypros_id', sa.String(length=16), nullable=True),
    sa.Column('gsis_id', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_espn_id'), 'players', ['espn_id'], unique=False)
    op.create_index(op.f('ix_players_fantasypros_id'), 'players', ['fantasypros_id'], unique=False)
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index(op.f('ix_players_gsis_id'), 'players', ['gsis_id'], unique=False)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_index(op.f('ix_players_sleeper_id'), 'players', ['sleeper_id'], unique=False)
    op.create_index(op.f('ix_players_yahoo_id'), 'players', ['yahoo_id'], unique=False)
    op.create_table('projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('stat_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'source', 'season', 'week', name='uq_projection')
    )
    op.create_index(op.f('ix_projections_player_id'), 'projections', ['player_id'], unique=False)
    op.create_index(op.f('ix_projections_source'), 'projections', ['source'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=48), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_key', sa.String(length=48), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('manager_name', sa.String(length=128), nullable=True),
    sa.Column('is_my_team', sa.Boolean(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('points_for', sa.Float(), nullable=True),
    sa.Column('points_against', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_league_id'), 'teams', ['league_id'], unique=False)
    op.create_index(op.f('ix_teams_team_key'), 'teams', ['team_key'], unique=True)
    op.create_table('trade_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('trend_30d', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'source', 'format', name='uq_trade_value')
    )
    op.create_index(op.f('ix_trade_values_player_id'), 'trade_values', ['player_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('yahoo_transaction_key', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_league_id'), 'transactions', ['league_id'], unique=False)
    op.create_index(op.f('ix_transactions_yahoo_transaction_key'), 'transactions', ['yahoo_transaction_key'], unique=True)
    op.create_table('trending_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'source', 'kind', name='uq_trending')
    )
    op.create_index(op.f('ix_trending_signals_player_id'), 'trending_signals', ['player_id'], unique=False)
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'round', 'pick', name='uq_draft_pick')
    )
    op.create_index(op.f('ix_draft_picks_league_id'), 'draft_picks', ['league_id'], unique=False)
    op.create_table('league_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=4), nullable=False),
    sa.Column('percent_owned', sa.Float(), nullable=True),
    sa.Column('on_team_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['on_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'player_id', name='uq_league_player')
    )
    op.create_index(op.f('ix_league_players_league_id'), 'league_players', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_players_player_id'), 'league_players', ['player_id'], unique=False)
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_points', sa.Float(), nullable=True),
    sa.Column('away_points', sa.Float(), nullable=True),
    sa.Column('is_playoffs', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'week', 'home_team_id', 'away_team_id', name='uq_matchup')
    )
    op.create_index(op.f('ix_matchups_league_id'), 'matchups', ['league_id'], unique=False)
    op.create_table('roster_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('selected_position', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'week', 'player_id', name='uq_roster_slot')
    )
    op.create_index(op.f('ix_roster_slots_player_id'), 'roster_slots', ['player_id'], unique=False)
    op.create_index(op.f('ix_roster_slots_team_id'), 'roster_slots', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_slots_team_id'), table_name='roster_slots')
    op.drop_index(op.f('ix_roster_slots_player_id'), table_name='roster_slots')
    op.drop_table('roster_slots')
    op.drop_index(op.f('ix_matchups_league_id'), table_name='matchups')
    op.drop_table('matchups')
    op.drop_index(op.f('ix_league_players_player_id'), table_name='league_players')
    op.drop_index(op.f('ix_league_players_league_id'), table_name='league_players')
    op.drop_table('league_players')
    op.drop_index(op.f('ix_draft_picks_league_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_trending_signals_player_id'), table_name='trending_signals')
    op.drop_table('trending_signals')
    op.drop_index(op.f('ix_transactions_yahoo_transaction_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_league_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_trade_values_player_id'), table_name='trade_values')
    op.drop_table('trade_values')
    op.drop_index(op.f('ix_teams_team_key'), table_name='teams')
    op.drop_index(op.f('ix_teams_league_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_projections_source'), table_name='projections')
    op.drop_index(op.f('ix_projections_player_id'), table_name='projections')
    op.drop_table('projections')
    op.drop_index(op.f('ix_players_yahoo_id'), table_name='players')
    op.drop_index(op.f('ix_players_sleeper_id'), table_name='players')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_gsis_id'), table_name='players')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_index(op.f('ix_players_fantasypros_id'), table_name='players')
    op.drop_index(op.f('ix_players_espn_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_leagues_league_key'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('app_users')
    # ### end Alembic commands ###
